# Generated by Django 4.0.5 on 2022-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorías',
            fields=[
                ('idCategoría', models.IntegerField(primary_key=True, serialize=False, verbose_name=' ID DE LA CATEGORIA ')),
                ('NombreCategoría', models.CharField(max_length=50, verbose_name=' NOMBRE DE LA CATEGORIA ')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IDProducto', models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name=' ID PRODUCTO ')),
                ('NombreProducto', models.CharField(max_length=20, verbose_name=' NOMBRE PRODUCTO ')),
                ('MarcaProducto', models.CharField(max_length=20, verbose_name=' MARCA ')),
                ('PrecioProducto', models.IntegerField(max_length=8, verbose_name=' PRECIO ')),
            ],
        ),
    ]
