# Generated by Django 3.2.13 on 2022-07-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorías',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
