# Generated by Django 3.2.13 on 2022-07-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boleta_categoria_cuenta_cliente_producto_subcripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_cliente',
            name='sub_usu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcripcion'),
        ),
    ]
